# Copyright (c) 2026 Evan Darwin - FSL-1.1-ALv2
"""The MLX device (Apple silicon, one memory for the CPU and the GPU): the host tier's weights as MLX arrays in
unified memory, zero-copy views between torch and MLX, whole layers as one graph per token. `core` (dtypes,
conversions, shared buffers), `gemv` (the matvec and MXFP4 kernels), `attn` (the node kernel, rope for rows,
the int8 cache), `delta` (the DeltaNet), `backend` (what an engine holds)."""

from .attn import (
    ATTN_MAXG,
    attn_decode,
    attn_nodes,
    attn_params,
    attn_prefill,
    attn_rows,
    attn_splits,
    attn_tree,
    attn_window_start,
    forest_meta,
    kv_dequantize,
    kv_quantize,
    rope_rows,
    rope_rows2,
    rows_meta,
    tree_meta,
)
from .backend import Backend, Weight
from .core import Shared, _dtypes, available, bf16_weight, from_mx, info, mx, shared_tensor, to_mx, torch_dtype
from .delta import (
    delta_chain_state,
    delta_chunk_prefill,
    delta_prefill,
    delta_recurrent,
    delta_step_fn,
    delta_tree,
    delta_tree_step,
)
from .gemv import (
    GEMV_ROWS,
    MXFP4_BLOCK,
    MXFP4_BLOCK_BYTES,
    experts_mxfp4_step,
    gemv,
    gemv_f32,
    gemv_mxfp4,
    gemv_mxfp4_group,
    gemv_mxfp4_pair,
    matmul_mxfp4,
    matmul_mxfp4_pair,
    mxfp4_bytes,
    mxfp4_dequant,
    mxfp4_split,
    read_bps,
    unpack_bf16,
)
from .kv import kv_gather, kv_store

__all__ = [
    "ATTN_MAXG",
    "GEMV_ROWS",
    "MXFP4_BLOCK",
    "MXFP4_BLOCK_BYTES",
    "Backend",
    "Shared",
    "Weight",
    "_dtypes",
    "attn_decode",
    "attn_nodes",
    "attn_params",
    "attn_prefill",
    "attn_rows",
    "attn_splits",
    "attn_tree",
    "attn_window_start",
    "available",
    "bf16_weight",
    "delta_chain_state",
    "delta_chunk_prefill",
    "delta_prefill",
    "delta_recurrent",
    "delta_step_fn",
    "delta_tree",
    "delta_tree_step",
    "experts_mxfp4_step",
    "forest_meta",
    "from_mx",
    "gemv",
    "gemv_f32",
    "gemv_mxfp4",
    "gemv_mxfp4_group",
    "gemv_mxfp4_pair",
    "info",
    "kv_dequantize",
    "kv_gather",
    "kv_quantize",
    "kv_store",
    "matmul_mxfp4",
    "matmul_mxfp4_pair",
    "mx",
    "mxfp4_bytes",
    "mxfp4_dequant",
    "mxfp4_split",
    "read_bps",
    "rope_rows",
    "rope_rows2",
    "rows_meta",
    "shared_tensor",
    "to_mx",
    "torch_dtype",
    "tree_meta",
    "unpack_bf16",
]
